# Generated by Django 2.2.6 on 2019-10-23 13:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('short_description', models.CharField(max_length=1024)),
                ('long_description', models.CharField(max_length=2048)),
                ('url', models.CharField(blank=True, max_length=512)),
                ('language_from', models.CharField(db_index=True, max_length=64)),
                ('language_to', models.CharField(db_index=True, max_length=64)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=256)),
                ('word_simplified', models.CharField(db_index=True, max_length=256)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Dictionary')),
            ],
        ),
    ]
