# Generated by Django 2.2.6 on 2019-10-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={'verbose_name_plural': 'dictionaries'},
        ),
        migrations.AddField(
            model_name='dictionary',
            name='allows_scraping',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='word_url_pattern',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='url',
            field=models.URLField(blank=True, max_length=512),
        ),
    ]
